// projects array

export default [
  {
    id: 1,
    name: 'The House Store ',
    url: 'https://the-house-store.ml',
    repos: 'https://github.com/Achraf-Ayadi/The-Store-House',
    img: './images/the-store-house.png',
    skills: [],
  },
  {
    id: 2,
    name: 'The Beach Resort',
    // url: 'https://the-house-store.ml',
    repos: 'https://github.com/Achraf-Ayadi/Beach-Resort',
    // img: './images/',
    skills: [],
  },
  {
    id: 3,
    name: 'Github User Search',
    url: 'https://github-user.ml',
    repos: 'https://github.com/Achraf-Ayadi/Github-user-search',
    img: './images/githubUser.png',
    skills: [],
  },
  ,
  {
    id: 4,
    name: 'To Do App',
    url: 'https://todo-app.tk',
    repos: 'https://github.com/Achraf-Ayadi/grocery-bud-React',
    img: './images/ToDoApp.png',
    skills: [],
  },
  ,
  {
    id: 5,
    name: 'Movie App',
    url: 'https://movie-app.ml',
    repos: 'https://github.com/Achraf-Ayadi/movie-React',
    img: './images/movie.png',
    skills: [],
  },
  ,
  {
    id: 6,
    name: 'Stock Photos',
    url: 'https://stock-photos.ml',
    repos: 'https://github.com/Achraf-Ayadi/stock-photos-React',
    img: './images/stock-photos.png',
    skills: [],
  },
  ,
  {
    id: 7,
    name: 'Menu Search',
    url: 'https://menu-search.ml',
    repos: 'https://github.com/Achraf-Ayadi/menu-React',
    img: './images/menu.png',
    skills: [],
  },
  ,
  {
    id: 8,
    name: 'Pagination',
    url: 'https://pagination.ml',
    repos: 'https://github.com/Achraf-Ayadi/pagination-React',
    img: './images/pagination.png',
    skills: [],
  },
  ,
  {
    id: 9,
    name: 'Cocktail',
    url: 'https://cocktail-app.ml',
    repos: 'https://github.com/Achraf-Ayadi/React-Project-Cocktail',
    img: './images/cocktail.png',
    skills: [],
  },
  ,
  {
    id: 10,
    name: 'Quiz',
    url: 'http://quiz-app.cf',
    repos: 'https://github.com/Achraf-Ayadi/quiz-React',
    img: './images/quiz.png',
    skills: [],
  },
  ,
  {
    id: 11,
    name: 'Hacker News',
    url: 'https://hacker-news.tk',
    repos: 'https://github.com/Achraf-Ayadi/hacker-news-React',
    img: './images/hacker-news.png',
    skills: [],
  },
]
